liberapay: 0rax
custom: ["https://paypal.me/0rax"]

# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
